# Generated by Django 3.2.5 on 2022-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_url',
            field=models.CharField(max_length=512, verbose_name='产品图片'),
        ),
    ]
