# Generated by Django 3.2.5 on 2022-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220517_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_url',
            field=models.CharField(blank=True, default=' ', max_length=512, verbose_name='产品图片'),
        ),
    ]
